### ISSUE TITLE
Stiebel Eltron WPL-20A some values (especially Temperatures) missing

### ISSUE THREAD

**Issue by chrissi5120** [pail23/stiebel_eltron_isg_component#1]
## Version of the custom_component
latest

## Configuration

stock-configuration

Add your logs here.

no issues in log

## Describe the bug
The home assistant integration is missing different temperatures which could be of interest:

![image](https://user-images.githubusercontent.com/11377607/190916811-5c56e3d5-b19b-4bd9-b077-35093ce86ac7.png)

could i provide you with some additional sensors for integration?

## Debug log

no debug-log

**Comment by pail23** [comment]
Hi @chrissi5120
Thanks for submitting the issue. I appreciate if you can submit a PR with sensors which are relevant to you.

**Comment by chrissi5120** [comment]
Its a lot to ask, i know.. but could you give me a little hint on how to identify the sensor names/ID's? 

I have no idea how to access the raw values from the ISG but i am fluent on the shell :) 
After i figured out how to do this, i will create a PR


best regards

Christoph

**Comment by pail23** [comment]
Here you can find the modbus register documentation: https://www.stiebel-eltron.de/content/dam/ste/cdbassets/current/bedienungs-_u_installationsanleitungen/isg_web_installationmanual_doc-00067703.pdf

You need to update `read_modbus_system_values(self)` in __init__. py in order to parse the registers. After that you need to update the `SYSTEM_VALUES_SENSOR_TYPES` in costs.py

**Comment by chrissi5120** [comment]
Hi @pail23, i created the pull-request #2 to add some additional sensors

thank you very much for your kind help.

**Comment by pail23** [comment]
Implementation merged
