### ISSUE TITLE
Missing Parameter for a brine heat Pump

### ISSUE THREAD

**Issue by abard35** [pail23/stiebel_eltron_isg_component#176]
Hi Paul,

possible to show them also in HA?

I'm trying to understand to what extent consumption could be related to these parameters.
And whether the difference is constant.

Unfortunately I don't even know where the values ​​are measured.
The borehole itself is 160 meters deep and usually deviates by around 3 degrees

Kind regards 
Albert
![HP](https://github.com/pail23/stiebel_eltron_isg_component/assets/97988225/ee676c10-c4e1-47e9-b0da-8e8c74900eaa)

**Comment by Padanian** [comment]
In HPG-I 04-15 the temperature sensors on the geothermal side are connected to the IWS, not to the WPM. The probes connected to the IWS are process probes, not temperature control probes. Register 536 queries input X1.9 of the WPM, to which nothing is connected, so the controller's response is in fact an off scale value (probe not connected). 
ISG can visualise the values of the process probes, because it queries the canbus, on which the process probes BT25 and 26 are available.
There are no plans to duplicate the readings of the process probes BT25 and 26 of the IWS from the canbus network to the modbus port.

**Comment by abard35** [comment]
Thank you for the very detailed answer!

**Comment by pail23** [comment]
So does this mean we can't implement the request with the current modbus implementiation of the ISG and therefore close this issue?

**Comment by Padanian** [comment]
Exactly. Can't fix.
