### ISSUE TITLE
Best energy dashboards layout + feature request.

### ISSUE THREAD

**Issue by Padanian** [pail23/stiebel_eltron_isg_component#214]
Not an issue. I would like to see what others have achieved with this extension. We might feature the best dashboards in a post on Stiebel Eltron social networks, credit will be given to the creator.
I'd like to appreciate most feature rich dashboards and best graphical layout.
Express yourselves.

Additionally, please mention two or three items you would like to be implemented in this extension or what you are missing most and would find useful.

**Comment by andreabafile** [comment]
I've recently built a dashboard since end users don't have access to servicewelt data and I wanted to have graphical data of my system to monitor and improve performances.
My aim was to:
1) monitor on/off of each heat pump by day
2) have immediate understanding of which heat pump is running and what the system is doing (DHW, Heating, Defrost) and 3) tracking COP.

Relevant pictures of the dashboard below. Maybe not super nice, but very effective to me:

1) Overall dashboard
<img width="1385" alt="Screenshot 2024-04-09 alle 21 11 56" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/109160754/038bad39-11f8-4ead-b89f-40cbf357afec">


2) Focus on current system status
<img width="360" alt="Screenshot 2024-04-09 alle 20 57 30" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/109160754/fab3f158-53fa-46e1-a970-6407cde52a05">


3) Focus on on/off and daily system status
<img width="355" alt="Screenshot 2024-04-09 alle 20 58 00" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/109160754/03d1a731-f2d8-4ba9-a139-b934dfe619d2">



Thanks to the dashboard graphs I managed to sensibly improve performances on my heating system.
It's an essential companion now.

Feature requests:
- Today produced heating and Today consumed energy should have at least 1 decimal, since it is not rounding up. For example, 1,9kWh of energy consumed, it's shown as just 1kWh. See below:
<img width="337" alt="Screenshot 2024-04-08 alle 21 18 26" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/109160754/2d3dc48f-af99-46dd-9d41-b2c668c44ac1">

- I'd love to have a sensor for the KelvinMinutes integral, but I don't know if it's transmitted over Modbus
- I'd also love to see the real time inverter power consumption by heat pump, but again I don't know if it's transmitted over Modbus.

Thank you for your dedication and help in improving this Home Assistant integration!

**Comment by pail23** [comment]
Since this is not an issue in the code, I propose to move this discussion to the [discussion forum](https://github.com/pail23/stiebel_eltron_isg_component/discussions).
@Padanian Please kick it of in the discussion forum again

**Comment by bitte-ein-bit** [comment]
@pail23 I'm not sure I've found an answer to the feature request hidden in here:

> Today produced heating and Today consumed energy should have at least 1 decimal, since it is not rounding up. For example, 1,9kWh of energy consumed, it's shown as just 1kWh.

Is this something doable? Loosing almost 1kWh will throw off all COP calculations.

Thank you
