### ISSUE TITLE
get compressor starts with wpm3

### ISSUE THREAD

**Issue by chrissi5120** [pail23/stiebel_eltron_isg_component#5]
do you see any way possible getting "verdichter starts" or "compressor starts" from modbus?

I can't see it in their documentation for wpm3 but lwz devices.

this would be one hell of an interesting number to keep an eye on.

**Comment by kucerazdenek** [comment]
this can be done via history stats workaround. I created sensors according to this (number of compressor starts can be done via type count) for heating. from this you can also measure time when this sensor was on.

https://community.home-assistant.io/t/calculate-time-of-a-switch-in-a-certain-state/327802

 - platform: history_stats
    name: Stiebel Eltron Heating count - Daily
    entity_id: binary_sensor.stiebel_eltron_isg_is_heating
    state: "on"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

**Comment by chrissi5120** [comment]
Hi @kucerazdenek, 

thank you for your suggestion, it is very much appreciated.
In my particular case, this will sadly miss the point due to the fact, that water-heating AND heating can be a reason for a compressor starting. This is made "worse" by the fact that after the compressor is for example started for heating, it can just switch to water-heating without stopping. 

The number would count much, much more starts than there actually are.

Nonetheless, you just teached me something new about home-assistant, thank you :)

best regards

Christoph

**Comment by kucerazdenek** [comment]
Hi @chrissi5120 

I know about it, in my case number of starts is just indicative, to be aware when anything would go wrong. 
I don't care if it heats or heating water, I am interested by compressor starts as such.
From that reason I count only heating (not water heating), because in 9 of 10 occurrences, water heating precede heating or vice versa (thus count of compressor starts is still exact). Very rarely (about once/twice a day), I see situation, when it starts to heat, then switch to water heating and then back to heat and my sensor will count 2 starts instead of 1. It is something I can live with.
I never seen situation when it would only heat water, as when heat pump switches to summer mode, I use PV for water heating.

![image](https://user-images.githubusercontent.com/121700009/221569083-a48fe8b0-6488-4a64-ae08-a888d2ad4094.png)


Regards, Zdenek

**Comment by chrissi5120** [comment]
binary_sensor.stiebel_eltron_isg_compressor should be the solution, since it was implemented:

Somthing like this might work:

configuration.yaml:

`counter:
  stiebel_eltron_compressor_starts:
    name: "Stiebel Eltron ISG Compressor Starts"
    step: 1`

Automation:

`- id: track_stiebel_eltron_starts
  alias: "Track Stiebel Eltron Compressor Starts"
  trigger:
    platform: state
    entity_id: binary_sensor.stiebel_eltron_isg_compressor
    from: 'off'
    to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.stiebel_eltron_compressor_starts`
